/****** Object:  Table [pmm].[FileUpload]    Script Date: 7/23/2023 4:40:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [pmm].[FileUpload](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[Name] [VARCHAR](MAX) NOT NULL,
	[BinaryData] [VARBINARY](MAX) NOT NULL,
	[UploadedBy] [VARCHAR](MAX) NOT NULL,
	[UploadedDate] [DATE] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


SELECT * FROM HORNE.pmm.FileUpload AS fu